parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Suez\Bundle\PrometheusMonitoringBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Controller,Monitoring,Migrations,Tests,SuezPrometheusMonitoringBundle.php}'

    Suez\Bundle\PrometheusMonitoringBundle\Monitoring\HealthCheck\:
        resource: '../../Monitoring/HealthCheck/*'
        exclude: '../../Monitoring/HealthCheck/Checker/*'

    Suez\Bundle\PrometheusMonitoringBundle\Monitoring\Metric\:
        resource:  '../../Monitoring/Metric/*'

    Suez\Bundle\PrometheusMonitoringBundle\Monitoring\Metric\CollectorRegistry:
        arguments:
            $appCode: "%suez_prometheus_monitoring.app_code%"

    Suez\Bundle\PrometheusMonitoringBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']