parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Suez\Bundle\PrometheusMonitoringBundle\Monitoring\Checker\HealthChecker\ElasticChecker:
        tags: ['suez.prometheus_monitoring_checker']