parameters:
    influxdb_host: null
    influxdb_port: 8086
    influxdb_db: null

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Suez\Bundle\PrometheusMonitoringBundle\Monitoring\HealthCheck\Checker\InfluxChecker:
        calls:
            - [setDatabase, ['@?influxdb_database']]
            - [setDatabase, ['@?algatux_influx_db.connection.http']]
            - [setConnectionSettings, ['%influxdb_host%', '%influxdb_port%', '%influxdb_db%']]
        tags: ['suez.prometheus_monitoring_checker']