parameters:
    mongo_host: null
    mongo_port: 27017
    mongo_db: null

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Suez\Bundle\PrometheusMonitoringBundle\Monitoring\HealthCheck\Checker\MongoChecker:
        calls:
            - [setDatabase, ['@?mongo_database']]
            - [setConnectionSettings, ['%mongo_host%', '%mongo_port%', '%mongo_db%']]
        tags: ['suez.prometheus_monitoring_checker']