parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Suez\Bundle\PrometheusMonitoringBundle\Monitoring\HealthCheck\Checker\MysqlChecker:
        tags: ['suez.prometheus_monitoring_checker']